---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: apache-artemis
    name: artemis-client
  spec:
    ports:
    - name: amqp
      port: 61616
      protocol: TCP
      targetPort: 61616
    selector:
      app: apache-artemis
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: apache-artemis
    name: artemis-web
  spec:
    type: NodePort
    ports:
    - name: http
      port: 8161
      protocol: TCP
      targetPort: 8161
    selector:
      app: apache-artemis
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: apache-artemis
    name: apache-artemis
  spec:
    replicas: 1
    selector:
      app: apache-artemis
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: apache-artemis
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Xms512m -Xmx512m -Dhawtio.authenticationEnabled=false
          image: kameshsampath/apache-artemis:2.4.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 61616
          name: apache-artemis
          ports:
          - containerPort: 61616
            name: core
          readinessProbe:
            httpGet:
              path: /console
              port: 8161
            initialDelaySeconds: 10
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: apache-artemis
    name: artemis-client
  spec:
    port:
      targetPort: 61616
    to:
      kind: Service
      name: artemis-client
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      expose: "true"
      app: apache-artemis
    name: artemis-web
  spec:
    port:
      targetPort: 8161
    to:
      kind: Service
      name: artemis-web
